spring.application.name=transfer-request
spring.datasource.url=jdbc:postgresql://localhost:5432/transfer_db
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=transfer_request_service
currentSchema=transfer_request_service

mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=30
mybatis.configuration.call-setters-on-nulls=true
mybatis.configuration-properties.schema=transfer_request_service
mybatis.type-handlers-package=com.eduproject.transferrequest.dao.mapper

limit.event-processor=1
scheduler.eventSending.initialDelayInitialSeconds=1000
scheduler.eventSending.fixedDelayInitialSeconds=1000

scheduler.event-sending-processor.executor-thread-nae-prefix=event-sch-
scheduler.event-sending-processor.pool-size=1
scheduler.event-sending-processor.shut-down-await=30

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5
spring.kafka.producer.properties.delivery.timeout.ms=30000
spring.kafka.producer.properties.request.timeout.ms=10000

app.kafka.topic.transfer-requested=transfer.requested
app.kafka.topic.transfer-requested.partitions=6
