spring.application.name=transfer-processing

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/transfer_db
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
currentSchema=transfer_processing_service

mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=30
mybatis.configuration.call-setters-on-nulls=true
mybatis.configuration-properties.schema=transfer_processing_service
mybatis.type-handlers-package=com.eduproject.transferprocessing.dao.mapper

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=transfer_processing_service

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=transfer-processing-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.eduproject.transferprocessing.dto
spring.kafka.consumer.properties.spring.json.value.default.type=com.eduproject.transferprocessing.dto.event.TransferRequestedEvent

app.kafka.topic.transfer-requested=transfer.requested